spring:
  jpa:
    hibernate:
      ddl-auto: create-drop  # или create, create-drop, none в зависимости от ваших нужд
    show-sql: true  # чтобы видеть SQL-запросы в консоли
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---
# Профиль 'prod' (активируется явно)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5439/progress
    username: testuser
    password: Pass8ord
    driver-class-name: org.postgresql.Driver

---
# Профиль h2
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console